/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.TFGInformatica;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ContaminacionEstacionDeMedicion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3722606105112444474L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContaminacionEstacionDeMedicion\",\"namespace\":\"org.TFGInformatica\",\"fields\":[{\"name\":\"idelem\",\"type\":\"int\"},{\"name\":\"no\",\"type\":[\"float\",\"null\"]},{\"name\":\"no2\",\"type\":[\"float\",\"null\"]},{\"name\":\"pm25\",\"type\":[\"float\",\"null\"]},{\"name\":\"pm10\",\"type\":[\"float\",\"null\"]},{\"name\":\"nox\",\"type\":[\"float\",\"null\"]},{\"name\":\"o3\",\"type\":[\"float\",\"null\"]},{\"name\":\"fechaActualizacion\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContaminacionEstacionDeMedicion> ENCODER =
      new BinaryMessageEncoder<ContaminacionEstacionDeMedicion>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContaminacionEstacionDeMedicion> DECODER =
      new BinaryMessageDecoder<ContaminacionEstacionDeMedicion>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContaminacionEstacionDeMedicion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContaminacionEstacionDeMedicion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContaminacionEstacionDeMedicion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContaminacionEstacionDeMedicion>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContaminacionEstacionDeMedicion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContaminacionEstacionDeMedicion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContaminacionEstacionDeMedicion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContaminacionEstacionDeMedicion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int idelem;
   private java.lang.Float no;
   private java.lang.Float no2;
   private java.lang.Float pm25;
   private java.lang.Float pm10;
   private java.lang.Float nox;
   private java.lang.Float o3;
   private java.lang.CharSequence fechaActualizacion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContaminacionEstacionDeMedicion() {}

  /**
   * All-args constructor.
   * @param idelem The new value for idelem
   * @param no The new value for no
   * @param no2 The new value for no2
   * @param pm25 The new value for pm25
   * @param pm10 The new value for pm10
   * @param nox The new value for nox
   * @param o3 The new value for o3
   * @param fechaActualizacion The new value for fechaActualizacion
   */
  public ContaminacionEstacionDeMedicion(java.lang.Integer idelem, java.lang.Float no, java.lang.Float no2, java.lang.Float pm25, java.lang.Float pm10, java.lang.Float nox, java.lang.Float o3, java.lang.CharSequence fechaActualizacion) {
    this.idelem = idelem;
    this.no = no;
    this.no2 = no2;
    this.pm25 = pm25;
    this.pm10 = pm10;
    this.nox = nox;
    this.o3 = o3;
    this.fechaActualizacion = fechaActualizacion;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idelem;
    case 1: return no;
    case 2: return no2;
    case 3: return pm25;
    case 4: return pm10;
    case 5: return nox;
    case 6: return o3;
    case 7: return fechaActualizacion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idelem = (java.lang.Integer)value$; break;
    case 1: no = (java.lang.Float)value$; break;
    case 2: no2 = (java.lang.Float)value$; break;
    case 3: pm25 = (java.lang.Float)value$; break;
    case 4: pm10 = (java.lang.Float)value$; break;
    case 5: nox = (java.lang.Float)value$; break;
    case 6: o3 = (java.lang.Float)value$; break;
    case 7: fechaActualizacion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idelem' field.
   * @return The value of the 'idelem' field.
   */
  public int getIdelem() {
    return idelem;
  }


  /**
   * Sets the value of the 'idelem' field.
   * @param value the value to set.
   */
  public void setIdelem(int value) {
    this.idelem = value;
  }

  /**
   * Gets the value of the 'no' field.
   * @return The value of the 'no' field.
   */
  public java.lang.Float getNo() {
    return no;
  }


  /**
   * Sets the value of the 'no' field.
   * @param value the value to set.
   */
  public void setNo(java.lang.Float value) {
    this.no = value;
  }

  /**
   * Gets the value of the 'no2' field.
   * @return The value of the 'no2' field.
   */
  public java.lang.Float getNo2() {
    return no2;
  }


  /**
   * Sets the value of the 'no2' field.
   * @param value the value to set.
   */
  public void setNo2(java.lang.Float value) {
    this.no2 = value;
  }

  /**
   * Gets the value of the 'pm25' field.
   * @return The value of the 'pm25' field.
   */
  public java.lang.Float getPm25() {
    return pm25;
  }


  /**
   * Sets the value of the 'pm25' field.
   * @param value the value to set.
   */
  public void setPm25(java.lang.Float value) {
    this.pm25 = value;
  }

  /**
   * Gets the value of the 'pm10' field.
   * @return The value of the 'pm10' field.
   */
  public java.lang.Float getPm10() {
    return pm10;
  }


  /**
   * Sets the value of the 'pm10' field.
   * @param value the value to set.
   */
  public void setPm10(java.lang.Float value) {
    this.pm10 = value;
  }

  /**
   * Gets the value of the 'nox' field.
   * @return The value of the 'nox' field.
   */
  public java.lang.Float getNox() {
    return nox;
  }


  /**
   * Sets the value of the 'nox' field.
   * @param value the value to set.
   */
  public void setNox(java.lang.Float value) {
    this.nox = value;
  }

  /**
   * Gets the value of the 'o3' field.
   * @return The value of the 'o3' field.
   */
  public java.lang.Float getO3() {
    return o3;
  }


  /**
   * Sets the value of the 'o3' field.
   * @param value the value to set.
   */
  public void setO3(java.lang.Float value) {
    this.o3 = value;
  }

  /**
   * Gets the value of the 'fechaActualizacion' field.
   * @return The value of the 'fechaActualizacion' field.
   */
  public java.lang.CharSequence getFechaActualizacion() {
    return fechaActualizacion;
  }


  /**
   * Sets the value of the 'fechaActualizacion' field.
   * @param value the value to set.
   */
  public void setFechaActualizacion(java.lang.CharSequence value) {
    this.fechaActualizacion = value;
  }

  /**
   * Creates a new ContaminacionEstacionDeMedicion RecordBuilder.
   * @return A new ContaminacionEstacionDeMedicion RecordBuilder
   */
  public static org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder newBuilder() {
    return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder();
  }

  /**
   * Creates a new ContaminacionEstacionDeMedicion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContaminacionEstacionDeMedicion RecordBuilder
   */
  public static org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder newBuilder(org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder other) {
    if (other == null) {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder();
    } else {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder(other);
    }
  }

  /**
   * Creates a new ContaminacionEstacionDeMedicion RecordBuilder by copying an existing ContaminacionEstacionDeMedicion instance.
   * @param other The existing instance to copy.
   * @return A new ContaminacionEstacionDeMedicion RecordBuilder
   */
  public static org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder newBuilder(org.TFGInformatica.ContaminacionEstacionDeMedicion other) {
    if (other == null) {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder();
    } else {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContaminacionEstacionDeMedicion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContaminacionEstacionDeMedicion>
    implements org.apache.avro.data.RecordBuilder<ContaminacionEstacionDeMedicion> {

    private int idelem;
    private java.lang.Float no;
    private java.lang.Float no2;
    private java.lang.Float pm25;
    private java.lang.Float pm10;
    private java.lang.Float nox;
    private java.lang.Float o3;
    private java.lang.CharSequence fechaActualizacion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idelem)) {
        this.idelem = data().deepCopy(fields()[0].schema(), other.idelem);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.no)) {
        this.no = data().deepCopy(fields()[1].schema(), other.no);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.no2)) {
        this.no2 = data().deepCopy(fields()[2].schema(), other.no2);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.pm25)) {
        this.pm25 = data().deepCopy(fields()[3].schema(), other.pm25);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.pm10)) {
        this.pm10 = data().deepCopy(fields()[4].schema(), other.pm10);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.nox)) {
        this.nox = data().deepCopy(fields()[5].schema(), other.nox);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.o3)) {
        this.o3 = data().deepCopy(fields()[6].schema(), other.o3);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.fechaActualizacion)) {
        this.fechaActualizacion = data().deepCopy(fields()[7].schema(), other.fechaActualizacion);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing ContaminacionEstacionDeMedicion instance
     * @param other The existing instance to copy.
     */
    private Builder(org.TFGInformatica.ContaminacionEstacionDeMedicion other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.idelem)) {
        this.idelem = data().deepCopy(fields()[0].schema(), other.idelem);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.no)) {
        this.no = data().deepCopy(fields()[1].schema(), other.no);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.no2)) {
        this.no2 = data().deepCopy(fields()[2].schema(), other.no2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pm25)) {
        this.pm25 = data().deepCopy(fields()[3].schema(), other.pm25);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pm10)) {
        this.pm10 = data().deepCopy(fields()[4].schema(), other.pm10);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.nox)) {
        this.nox = data().deepCopy(fields()[5].schema(), other.nox);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.o3)) {
        this.o3 = data().deepCopy(fields()[6].schema(), other.o3);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.fechaActualizacion)) {
        this.fechaActualizacion = data().deepCopy(fields()[7].schema(), other.fechaActualizacion);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'idelem' field.
      * @return The value.
      */
    public int getIdelem() {
      return idelem;
    }


    /**
      * Sets the value of the 'idelem' field.
      * @param value The value of 'idelem'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setIdelem(int value) {
      validate(fields()[0], value);
      this.idelem = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idelem' field has been set.
      * @return True if the 'idelem' field has been set, false otherwise.
      */
    public boolean hasIdelem() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idelem' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearIdelem() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'no' field.
      * @return The value.
      */
    public java.lang.Float getNo() {
      return no;
    }


    /**
      * Sets the value of the 'no' field.
      * @param value The value of 'no'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setNo(java.lang.Float value) {
      validate(fields()[1], value);
      this.no = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'no' field has been set.
      * @return True if the 'no' field has been set, false otherwise.
      */
    public boolean hasNo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'no' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearNo() {
      no = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'no2' field.
      * @return The value.
      */
    public java.lang.Float getNo2() {
      return no2;
    }


    /**
      * Sets the value of the 'no2' field.
      * @param value The value of 'no2'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setNo2(java.lang.Float value) {
      validate(fields()[2], value);
      this.no2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'no2' field has been set.
      * @return True if the 'no2' field has been set, false otherwise.
      */
    public boolean hasNo2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'no2' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearNo2() {
      no2 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'pm25' field.
      * @return The value.
      */
    public java.lang.Float getPm25() {
      return pm25;
    }


    /**
      * Sets the value of the 'pm25' field.
      * @param value The value of 'pm25'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setPm25(java.lang.Float value) {
      validate(fields()[3], value);
      this.pm25 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'pm25' field has been set.
      * @return True if the 'pm25' field has been set, false otherwise.
      */
    public boolean hasPm25() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'pm25' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearPm25() {
      pm25 = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'pm10' field.
      * @return The value.
      */
    public java.lang.Float getPm10() {
      return pm10;
    }


    /**
      * Sets the value of the 'pm10' field.
      * @param value The value of 'pm10'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setPm10(java.lang.Float value) {
      validate(fields()[4], value);
      this.pm10 = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'pm10' field has been set.
      * @return True if the 'pm10' field has been set, false otherwise.
      */
    public boolean hasPm10() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'pm10' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearPm10() {
      pm10 = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'nox' field.
      * @return The value.
      */
    public java.lang.Float getNox() {
      return nox;
    }


    /**
      * Sets the value of the 'nox' field.
      * @param value The value of 'nox'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setNox(java.lang.Float value) {
      validate(fields()[5], value);
      this.nox = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'nox' field has been set.
      * @return True if the 'nox' field has been set, false otherwise.
      */
    public boolean hasNox() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'nox' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearNox() {
      nox = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'o3' field.
      * @return The value.
      */
    public java.lang.Float getO3() {
      return o3;
    }


    /**
      * Sets the value of the 'o3' field.
      * @param value The value of 'o3'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setO3(java.lang.Float value) {
      validate(fields()[6], value);
      this.o3 = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'o3' field has been set.
      * @return True if the 'o3' field has been set, false otherwise.
      */
    public boolean hasO3() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'o3' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearO3() {
      o3 = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaActualizacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getFechaActualizacion() {
      return fechaActualizacion;
    }


    /**
      * Sets the value of the 'fechaActualizacion' field.
      * @param value The value of 'fechaActualizacion'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setFechaActualizacion(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.fechaActualizacion = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaActualizacion' field has been set.
      * @return True if the 'fechaActualizacion' field has been set, false otherwise.
      */
    public boolean hasFechaActualizacion() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'fechaActualizacion' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearFechaActualizacion() {
      fechaActualizacion = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContaminacionEstacionDeMedicion build() {
      try {
        ContaminacionEstacionDeMedicion record = new ContaminacionEstacionDeMedicion();
        record.idelem = fieldSetFlags()[0] ? this.idelem : (java.lang.Integer) defaultValue(fields()[0]);
        record.no = fieldSetFlags()[1] ? this.no : (java.lang.Float) defaultValue(fields()[1]);
        record.no2 = fieldSetFlags()[2] ? this.no2 : (java.lang.Float) defaultValue(fields()[2]);
        record.pm25 = fieldSetFlags()[3] ? this.pm25 : (java.lang.Float) defaultValue(fields()[3]);
        record.pm10 = fieldSetFlags()[4] ? this.pm10 : (java.lang.Float) defaultValue(fields()[4]);
        record.nox = fieldSetFlags()[5] ? this.nox : (java.lang.Float) defaultValue(fields()[5]);
        record.o3 = fieldSetFlags()[6] ? this.o3 : (java.lang.Float) defaultValue(fields()[6]);
        record.fechaActualizacion = fieldSetFlags()[7] ? this.fechaActualizacion : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContaminacionEstacionDeMedicion>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContaminacionEstacionDeMedicion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContaminacionEstacionDeMedicion>
    READER$ = (org.apache.avro.io.DatumReader<ContaminacionEstacionDeMedicion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.idelem);

    if (this.no == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeFloat(this.no);
    }

    if (this.no2 == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeFloat(this.no2);
    }

    if (this.pm25 == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeFloat(this.pm25);
    }

    if (this.pm10 == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeFloat(this.pm10);
    }

    if (this.nox == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeFloat(this.nox);
    }

    if (this.o3 == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeFloat(this.o3);
    }

    out.writeString(this.fechaActualizacion);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idelem = in.readInt();

      if (in.readIndex() != 0) {
        in.readNull();
        this.no = null;
      } else {
        this.no = in.readFloat();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.no2 = null;
      } else {
        this.no2 = in.readFloat();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.pm25 = null;
      } else {
        this.pm25 = in.readFloat();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.pm10 = null;
      } else {
        this.pm10 = in.readFloat();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.nox = null;
      } else {
        this.nox = in.readFloat();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.o3 = null;
      } else {
        this.o3 = in.readFloat();
      }

      this.fechaActualizacion = in.readString(this.fechaActualizacion instanceof Utf8 ? (Utf8)this.fechaActualizacion : null);

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idelem = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.no = null;
          } else {
            this.no = in.readFloat();
          }
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.no2 = null;
          } else {
            this.no2 = in.readFloat();
          }
          break;

        case 3:
          if (in.readIndex() != 0) {
            in.readNull();
            this.pm25 = null;
          } else {
            this.pm25 = in.readFloat();
          }
          break;

        case 4:
          if (in.readIndex() != 0) {
            in.readNull();
            this.pm10 = null;
          } else {
            this.pm10 = in.readFloat();
          }
          break;

        case 5:
          if (in.readIndex() != 0) {
            in.readNull();
            this.nox = null;
          } else {
            this.nox = in.readFloat();
          }
          break;

        case 6:
          if (in.readIndex() != 0) {
            in.readNull();
            this.o3 = null;
          } else {
            this.o3 = in.readFloat();
          }
          break;

        case 7:
          this.fechaActualizacion = in.readString(this.fechaActualizacion instanceof Utf8 ? (Utf8)this.fechaActualizacion : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










