/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.TFGInformatica;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ContaminacionEstacionDeMedicion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9060368838604227222L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContaminacionEstacionDeMedicion\",\"namespace\":\"org.TFGInformatica\",\"fields\":[{\"name\":\"idelem\",\"type\":\"int\"},{\"name\":\"descripcion\",\"type\":\"string\"},{\"name\":\"m01\",\"type\":\"float\"},{\"name\":\"m06\",\"type\":\"float\"},{\"name\":\"m07\",\"type\":\"float\"},{\"name\":\"m08\",\"type\":\"float\"},{\"name\":\"m09\",\"type\":\"float\"},{\"name\":\"m10\",\"type\":\"float\"},{\"name\":\"m12\",\"type\":\"float\"},{\"name\":\"m14\",\"type\":\"float\"},{\"name\":\"m20\",\"type\":\"float\"},{\"name\":\"m30\",\"type\":\"float\"},{\"name\":\"m35\",\"type\":\"float\"},{\"name\":\"m37\",\"type\":\"float\"},{\"name\":\"m38\",\"type\":\"float\"},{\"name\":\"m39\",\"type\":\"float\"},{\"name\":\"m42\",\"type\":\"float\"},{\"name\":\"m43\",\"type\":\"float\"},{\"name\":\"fechaActualizacion\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContaminacionEstacionDeMedicion> ENCODER =
      new BinaryMessageEncoder<ContaminacionEstacionDeMedicion>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContaminacionEstacionDeMedicion> DECODER =
      new BinaryMessageDecoder<ContaminacionEstacionDeMedicion>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContaminacionEstacionDeMedicion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContaminacionEstacionDeMedicion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContaminacionEstacionDeMedicion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContaminacionEstacionDeMedicion>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContaminacionEstacionDeMedicion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContaminacionEstacionDeMedicion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContaminacionEstacionDeMedicion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContaminacionEstacionDeMedicion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int idelem;
   private java.lang.CharSequence descripcion;
   private float m01;
   private float m06;
   private float m07;
   private float m08;
   private float m09;
   private float m10;
   private float m12;
   private float m14;
   private float m20;
   private float m30;
   private float m35;
   private float m37;
   private float m38;
   private float m39;
   private float m42;
   private float m43;
   private java.lang.CharSequence fechaActualizacion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContaminacionEstacionDeMedicion() {}

  /**
   * All-args constructor.
   * @param idelem The new value for idelem
   * @param descripcion The new value for descripcion
   * @param m01 The new value for m01
   * @param m06 The new value for m06
   * @param m07 The new value for m07
   * @param m08 The new value for m08
   * @param m09 The new value for m09
   * @param m10 The new value for m10
   * @param m12 The new value for m12
   * @param m14 The new value for m14
   * @param m20 The new value for m20
   * @param m30 The new value for m30
   * @param m35 The new value for m35
   * @param m37 The new value for m37
   * @param m38 The new value for m38
   * @param m39 The new value for m39
   * @param m42 The new value for m42
   * @param m43 The new value for m43
   * @param fechaActualizacion The new value for fechaActualizacion
   */
  public ContaminacionEstacionDeMedicion(java.lang.Integer idelem, java.lang.CharSequence descripcion, java.lang.Float m01, java.lang.Float m06, java.lang.Float m07, java.lang.Float m08, java.lang.Float m09, java.lang.Float m10, java.lang.Float m12, java.lang.Float m14, java.lang.Float m20, java.lang.Float m30, java.lang.Float m35, java.lang.Float m37, java.lang.Float m38, java.lang.Float m39, java.lang.Float m42, java.lang.Float m43, java.lang.CharSequence fechaActualizacion) {
    this.idelem = idelem;
    this.descripcion = descripcion;
    this.m01 = m01;
    this.m06 = m06;
    this.m07 = m07;
    this.m08 = m08;
    this.m09 = m09;
    this.m10 = m10;
    this.m12 = m12;
    this.m14 = m14;
    this.m20 = m20;
    this.m30 = m30;
    this.m35 = m35;
    this.m37 = m37;
    this.m38 = m38;
    this.m39 = m39;
    this.m42 = m42;
    this.m43 = m43;
    this.fechaActualizacion = fechaActualizacion;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idelem;
    case 1: return descripcion;
    case 2: return m01;
    case 3: return m06;
    case 4: return m07;
    case 5: return m08;
    case 6: return m09;
    case 7: return m10;
    case 8: return m12;
    case 9: return m14;
    case 10: return m20;
    case 11: return m30;
    case 12: return m35;
    case 13: return m37;
    case 14: return m38;
    case 15: return m39;
    case 16: return m42;
    case 17: return m43;
    case 18: return fechaActualizacion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idelem = (java.lang.Integer)value$; break;
    case 1: descripcion = (java.lang.CharSequence)value$; break;
    case 2: m01 = (java.lang.Float)value$; break;
    case 3: m06 = (java.lang.Float)value$; break;
    case 4: m07 = (java.lang.Float)value$; break;
    case 5: m08 = (java.lang.Float)value$; break;
    case 6: m09 = (java.lang.Float)value$; break;
    case 7: m10 = (java.lang.Float)value$; break;
    case 8: m12 = (java.lang.Float)value$; break;
    case 9: m14 = (java.lang.Float)value$; break;
    case 10: m20 = (java.lang.Float)value$; break;
    case 11: m30 = (java.lang.Float)value$; break;
    case 12: m35 = (java.lang.Float)value$; break;
    case 13: m37 = (java.lang.Float)value$; break;
    case 14: m38 = (java.lang.Float)value$; break;
    case 15: m39 = (java.lang.Float)value$; break;
    case 16: m42 = (java.lang.Float)value$; break;
    case 17: m43 = (java.lang.Float)value$; break;
    case 18: fechaActualizacion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idelem' field.
   * @return The value of the 'idelem' field.
   */
  public int getIdelem() {
    return idelem;
  }


  /**
   * Sets the value of the 'idelem' field.
   * @param value the value to set.
   */
  public void setIdelem(int value) {
    this.idelem = value;
  }

  /**
   * Gets the value of the 'descripcion' field.
   * @return The value of the 'descripcion' field.
   */
  public java.lang.CharSequence getDescripcion() {
    return descripcion;
  }


  /**
   * Sets the value of the 'descripcion' field.
   * @param value the value to set.
   */
  public void setDescripcion(java.lang.CharSequence value) {
    this.descripcion = value;
  }

  /**
   * Gets the value of the 'm01' field.
   * @return The value of the 'm01' field.
   */
  public float getM01() {
    return m01;
  }


  /**
   * Sets the value of the 'm01' field.
   * @param value the value to set.
   */
  public void setM01(float value) {
    this.m01 = value;
  }

  /**
   * Gets the value of the 'm06' field.
   * @return The value of the 'm06' field.
   */
  public float getM06() {
    return m06;
  }


  /**
   * Sets the value of the 'm06' field.
   * @param value the value to set.
   */
  public void setM06(float value) {
    this.m06 = value;
  }

  /**
   * Gets the value of the 'm07' field.
   * @return The value of the 'm07' field.
   */
  public float getM07() {
    return m07;
  }


  /**
   * Sets the value of the 'm07' field.
   * @param value the value to set.
   */
  public void setM07(float value) {
    this.m07 = value;
  }

  /**
   * Gets the value of the 'm08' field.
   * @return The value of the 'm08' field.
   */
  public float getM08() {
    return m08;
  }


  /**
   * Sets the value of the 'm08' field.
   * @param value the value to set.
   */
  public void setM08(float value) {
    this.m08 = value;
  }

  /**
   * Gets the value of the 'm09' field.
   * @return The value of the 'm09' field.
   */
  public float getM09() {
    return m09;
  }


  /**
   * Sets the value of the 'm09' field.
   * @param value the value to set.
   */
  public void setM09(float value) {
    this.m09 = value;
  }

  /**
   * Gets the value of the 'm10' field.
   * @return The value of the 'm10' field.
   */
  public float getM10() {
    return m10;
  }


  /**
   * Sets the value of the 'm10' field.
   * @param value the value to set.
   */
  public void setM10(float value) {
    this.m10 = value;
  }

  /**
   * Gets the value of the 'm12' field.
   * @return The value of the 'm12' field.
   */
  public float getM12() {
    return m12;
  }


  /**
   * Sets the value of the 'm12' field.
   * @param value the value to set.
   */
  public void setM12(float value) {
    this.m12 = value;
  }

  /**
   * Gets the value of the 'm14' field.
   * @return The value of the 'm14' field.
   */
  public float getM14() {
    return m14;
  }


  /**
   * Sets the value of the 'm14' field.
   * @param value the value to set.
   */
  public void setM14(float value) {
    this.m14 = value;
  }

  /**
   * Gets the value of the 'm20' field.
   * @return The value of the 'm20' field.
   */
  public float getM20() {
    return m20;
  }


  /**
   * Sets the value of the 'm20' field.
   * @param value the value to set.
   */
  public void setM20(float value) {
    this.m20 = value;
  }

  /**
   * Gets the value of the 'm30' field.
   * @return The value of the 'm30' field.
   */
  public float getM30() {
    return m30;
  }


  /**
   * Sets the value of the 'm30' field.
   * @param value the value to set.
   */
  public void setM30(float value) {
    this.m30 = value;
  }

  /**
   * Gets the value of the 'm35' field.
   * @return The value of the 'm35' field.
   */
  public float getM35() {
    return m35;
  }


  /**
   * Sets the value of the 'm35' field.
   * @param value the value to set.
   */
  public void setM35(float value) {
    this.m35 = value;
  }

  /**
   * Gets the value of the 'm37' field.
   * @return The value of the 'm37' field.
   */
  public float getM37() {
    return m37;
  }


  /**
   * Sets the value of the 'm37' field.
   * @param value the value to set.
   */
  public void setM37(float value) {
    this.m37 = value;
  }

  /**
   * Gets the value of the 'm38' field.
   * @return The value of the 'm38' field.
   */
  public float getM38() {
    return m38;
  }


  /**
   * Sets the value of the 'm38' field.
   * @param value the value to set.
   */
  public void setM38(float value) {
    this.m38 = value;
  }

  /**
   * Gets the value of the 'm39' field.
   * @return The value of the 'm39' field.
   */
  public float getM39() {
    return m39;
  }


  /**
   * Sets the value of the 'm39' field.
   * @param value the value to set.
   */
  public void setM39(float value) {
    this.m39 = value;
  }

  /**
   * Gets the value of the 'm42' field.
   * @return The value of the 'm42' field.
   */
  public float getM42() {
    return m42;
  }


  /**
   * Sets the value of the 'm42' field.
   * @param value the value to set.
   */
  public void setM42(float value) {
    this.m42 = value;
  }

  /**
   * Gets the value of the 'm43' field.
   * @return The value of the 'm43' field.
   */
  public float getM43() {
    return m43;
  }


  /**
   * Sets the value of the 'm43' field.
   * @param value the value to set.
   */
  public void setM43(float value) {
    this.m43 = value;
  }

  /**
   * Gets the value of the 'fechaActualizacion' field.
   * @return The value of the 'fechaActualizacion' field.
   */
  public java.lang.CharSequence getFechaActualizacion() {
    return fechaActualizacion;
  }


  /**
   * Sets the value of the 'fechaActualizacion' field.
   * @param value the value to set.
   */
  public void setFechaActualizacion(java.lang.CharSequence value) {
    this.fechaActualizacion = value;
  }

  /**
   * Creates a new ContaminacionEstacionDeMedicion RecordBuilder.
   * @return A new ContaminacionEstacionDeMedicion RecordBuilder
   */
  public static org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder newBuilder() {
    return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder();
  }

  /**
   * Creates a new ContaminacionEstacionDeMedicion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContaminacionEstacionDeMedicion RecordBuilder
   */
  public static org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder newBuilder(org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder other) {
    if (other == null) {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder();
    } else {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder(other);
    }
  }

  /**
   * Creates a new ContaminacionEstacionDeMedicion RecordBuilder by copying an existing ContaminacionEstacionDeMedicion instance.
   * @param other The existing instance to copy.
   * @return A new ContaminacionEstacionDeMedicion RecordBuilder
   */
  public static org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder newBuilder(org.TFGInformatica.ContaminacionEstacionDeMedicion other) {
    if (other == null) {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder();
    } else {
      return new org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContaminacionEstacionDeMedicion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContaminacionEstacionDeMedicion>
    implements org.apache.avro.data.RecordBuilder<ContaminacionEstacionDeMedicion> {

    private int idelem;
    private java.lang.CharSequence descripcion;
    private float m01;
    private float m06;
    private float m07;
    private float m08;
    private float m09;
    private float m10;
    private float m12;
    private float m14;
    private float m20;
    private float m30;
    private float m35;
    private float m37;
    private float m38;
    private float m39;
    private float m42;
    private float m43;
    private java.lang.CharSequence fechaActualizacion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idelem)) {
        this.idelem = data().deepCopy(fields()[0].schema(), other.idelem);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.descripcion)) {
        this.descripcion = data().deepCopy(fields()[1].schema(), other.descripcion);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.m01)) {
        this.m01 = data().deepCopy(fields()[2].schema(), other.m01);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.m06)) {
        this.m06 = data().deepCopy(fields()[3].schema(), other.m06);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.m07)) {
        this.m07 = data().deepCopy(fields()[4].schema(), other.m07);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.m08)) {
        this.m08 = data().deepCopy(fields()[5].schema(), other.m08);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.m09)) {
        this.m09 = data().deepCopy(fields()[6].schema(), other.m09);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.m10)) {
        this.m10 = data().deepCopy(fields()[7].schema(), other.m10);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.m12)) {
        this.m12 = data().deepCopy(fields()[8].schema(), other.m12);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.m14)) {
        this.m14 = data().deepCopy(fields()[9].schema(), other.m14);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.m20)) {
        this.m20 = data().deepCopy(fields()[10].schema(), other.m20);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.m30)) {
        this.m30 = data().deepCopy(fields()[11].schema(), other.m30);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.m35)) {
        this.m35 = data().deepCopy(fields()[12].schema(), other.m35);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.m37)) {
        this.m37 = data().deepCopy(fields()[13].schema(), other.m37);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.m38)) {
        this.m38 = data().deepCopy(fields()[14].schema(), other.m38);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.m39)) {
        this.m39 = data().deepCopy(fields()[15].schema(), other.m39);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.m42)) {
        this.m42 = data().deepCopy(fields()[16].schema(), other.m42);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.m43)) {
        this.m43 = data().deepCopy(fields()[17].schema(), other.m43);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.fechaActualizacion)) {
        this.fechaActualizacion = data().deepCopy(fields()[18].schema(), other.fechaActualizacion);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
    }

    /**
     * Creates a Builder by copying an existing ContaminacionEstacionDeMedicion instance
     * @param other The existing instance to copy.
     */
    private Builder(org.TFGInformatica.ContaminacionEstacionDeMedicion other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.idelem)) {
        this.idelem = data().deepCopy(fields()[0].schema(), other.idelem);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.descripcion)) {
        this.descripcion = data().deepCopy(fields()[1].schema(), other.descripcion);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.m01)) {
        this.m01 = data().deepCopy(fields()[2].schema(), other.m01);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.m06)) {
        this.m06 = data().deepCopy(fields()[3].schema(), other.m06);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.m07)) {
        this.m07 = data().deepCopy(fields()[4].schema(), other.m07);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.m08)) {
        this.m08 = data().deepCopy(fields()[5].schema(), other.m08);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.m09)) {
        this.m09 = data().deepCopy(fields()[6].schema(), other.m09);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.m10)) {
        this.m10 = data().deepCopy(fields()[7].schema(), other.m10);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.m12)) {
        this.m12 = data().deepCopy(fields()[8].schema(), other.m12);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.m14)) {
        this.m14 = data().deepCopy(fields()[9].schema(), other.m14);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.m20)) {
        this.m20 = data().deepCopy(fields()[10].schema(), other.m20);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.m30)) {
        this.m30 = data().deepCopy(fields()[11].schema(), other.m30);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.m35)) {
        this.m35 = data().deepCopy(fields()[12].schema(), other.m35);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.m37)) {
        this.m37 = data().deepCopy(fields()[13].schema(), other.m37);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.m38)) {
        this.m38 = data().deepCopy(fields()[14].schema(), other.m38);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.m39)) {
        this.m39 = data().deepCopy(fields()[15].schema(), other.m39);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.m42)) {
        this.m42 = data().deepCopy(fields()[16].schema(), other.m42);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.m43)) {
        this.m43 = data().deepCopy(fields()[17].schema(), other.m43);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.fechaActualizacion)) {
        this.fechaActualizacion = data().deepCopy(fields()[18].schema(), other.fechaActualizacion);
        fieldSetFlags()[18] = true;
      }
    }

    /**
      * Gets the value of the 'idelem' field.
      * @return The value.
      */
    public int getIdelem() {
      return idelem;
    }


    /**
      * Sets the value of the 'idelem' field.
      * @param value The value of 'idelem'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setIdelem(int value) {
      validate(fields()[0], value);
      this.idelem = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idelem' field has been set.
      * @return True if the 'idelem' field has been set, false otherwise.
      */
    public boolean hasIdelem() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idelem' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearIdelem() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'descripcion' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescripcion() {
      return descripcion;
    }


    /**
      * Sets the value of the 'descripcion' field.
      * @param value The value of 'descripcion'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setDescripcion(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.descripcion = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'descripcion' field has been set.
      * @return True if the 'descripcion' field has been set, false otherwise.
      */
    public boolean hasDescripcion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'descripcion' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearDescripcion() {
      descripcion = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'm01' field.
      * @return The value.
      */
    public float getM01() {
      return m01;
    }


    /**
      * Sets the value of the 'm01' field.
      * @param value The value of 'm01'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM01(float value) {
      validate(fields()[2], value);
      this.m01 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'm01' field has been set.
      * @return True if the 'm01' field has been set, false otherwise.
      */
    public boolean hasM01() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'm01' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM01() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'm06' field.
      * @return The value.
      */
    public float getM06() {
      return m06;
    }


    /**
      * Sets the value of the 'm06' field.
      * @param value The value of 'm06'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM06(float value) {
      validate(fields()[3], value);
      this.m06 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'm06' field has been set.
      * @return True if the 'm06' field has been set, false otherwise.
      */
    public boolean hasM06() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'm06' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM06() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'm07' field.
      * @return The value.
      */
    public float getM07() {
      return m07;
    }


    /**
      * Sets the value of the 'm07' field.
      * @param value The value of 'm07'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM07(float value) {
      validate(fields()[4], value);
      this.m07 = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'm07' field has been set.
      * @return True if the 'm07' field has been set, false otherwise.
      */
    public boolean hasM07() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'm07' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM07() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'm08' field.
      * @return The value.
      */
    public float getM08() {
      return m08;
    }


    /**
      * Sets the value of the 'm08' field.
      * @param value The value of 'm08'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM08(float value) {
      validate(fields()[5], value);
      this.m08 = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'm08' field has been set.
      * @return True if the 'm08' field has been set, false otherwise.
      */
    public boolean hasM08() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'm08' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM08() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'm09' field.
      * @return The value.
      */
    public float getM09() {
      return m09;
    }


    /**
      * Sets the value of the 'm09' field.
      * @param value The value of 'm09'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM09(float value) {
      validate(fields()[6], value);
      this.m09 = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'm09' field has been set.
      * @return True if the 'm09' field has been set, false otherwise.
      */
    public boolean hasM09() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'm09' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM09() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'm10' field.
      * @return The value.
      */
    public float getM10() {
      return m10;
    }


    /**
      * Sets the value of the 'm10' field.
      * @param value The value of 'm10'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM10(float value) {
      validate(fields()[7], value);
      this.m10 = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'm10' field has been set.
      * @return True if the 'm10' field has been set, false otherwise.
      */
    public boolean hasM10() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'm10' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM10() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'm12' field.
      * @return The value.
      */
    public float getM12() {
      return m12;
    }


    /**
      * Sets the value of the 'm12' field.
      * @param value The value of 'm12'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM12(float value) {
      validate(fields()[8], value);
      this.m12 = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'm12' field has been set.
      * @return True if the 'm12' field has been set, false otherwise.
      */
    public boolean hasM12() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'm12' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM12() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'm14' field.
      * @return The value.
      */
    public float getM14() {
      return m14;
    }


    /**
      * Sets the value of the 'm14' field.
      * @param value The value of 'm14'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM14(float value) {
      validate(fields()[9], value);
      this.m14 = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'm14' field has been set.
      * @return True if the 'm14' field has been set, false otherwise.
      */
    public boolean hasM14() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'm14' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM14() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'm20' field.
      * @return The value.
      */
    public float getM20() {
      return m20;
    }


    /**
      * Sets the value of the 'm20' field.
      * @param value The value of 'm20'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM20(float value) {
      validate(fields()[10], value);
      this.m20 = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'm20' field has been set.
      * @return True if the 'm20' field has been set, false otherwise.
      */
    public boolean hasM20() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'm20' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM20() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'm30' field.
      * @return The value.
      */
    public float getM30() {
      return m30;
    }


    /**
      * Sets the value of the 'm30' field.
      * @param value The value of 'm30'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM30(float value) {
      validate(fields()[11], value);
      this.m30 = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'm30' field has been set.
      * @return True if the 'm30' field has been set, false otherwise.
      */
    public boolean hasM30() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'm30' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM30() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'm35' field.
      * @return The value.
      */
    public float getM35() {
      return m35;
    }


    /**
      * Sets the value of the 'm35' field.
      * @param value The value of 'm35'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM35(float value) {
      validate(fields()[12], value);
      this.m35 = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'm35' field has been set.
      * @return True if the 'm35' field has been set, false otherwise.
      */
    public boolean hasM35() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'm35' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM35() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'm37' field.
      * @return The value.
      */
    public float getM37() {
      return m37;
    }


    /**
      * Sets the value of the 'm37' field.
      * @param value The value of 'm37'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM37(float value) {
      validate(fields()[13], value);
      this.m37 = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'm37' field has been set.
      * @return True if the 'm37' field has been set, false otherwise.
      */
    public boolean hasM37() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'm37' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM37() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'm38' field.
      * @return The value.
      */
    public float getM38() {
      return m38;
    }


    /**
      * Sets the value of the 'm38' field.
      * @param value The value of 'm38'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM38(float value) {
      validate(fields()[14], value);
      this.m38 = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'm38' field has been set.
      * @return True if the 'm38' field has been set, false otherwise.
      */
    public boolean hasM38() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'm38' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM38() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'm39' field.
      * @return The value.
      */
    public float getM39() {
      return m39;
    }


    /**
      * Sets the value of the 'm39' field.
      * @param value The value of 'm39'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM39(float value) {
      validate(fields()[15], value);
      this.m39 = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'm39' field has been set.
      * @return True if the 'm39' field has been set, false otherwise.
      */
    public boolean hasM39() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'm39' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM39() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'm42' field.
      * @return The value.
      */
    public float getM42() {
      return m42;
    }


    /**
      * Sets the value of the 'm42' field.
      * @param value The value of 'm42'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM42(float value) {
      validate(fields()[16], value);
      this.m42 = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'm42' field has been set.
      * @return True if the 'm42' field has been set, false otherwise.
      */
    public boolean hasM42() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'm42' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM42() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'm43' field.
      * @return The value.
      */
    public float getM43() {
      return m43;
    }


    /**
      * Sets the value of the 'm43' field.
      * @param value The value of 'm43'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setM43(float value) {
      validate(fields()[17], value);
      this.m43 = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'm43' field has been set.
      * @return True if the 'm43' field has been set, false otherwise.
      */
    public boolean hasM43() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'm43' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearM43() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'fechaActualizacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getFechaActualizacion() {
      return fechaActualizacion;
    }


    /**
      * Sets the value of the 'fechaActualizacion' field.
      * @param value The value of 'fechaActualizacion'.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder setFechaActualizacion(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.fechaActualizacion = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'fechaActualizacion' field has been set.
      * @return True if the 'fechaActualizacion' field has been set, false otherwise.
      */
    public boolean hasFechaActualizacion() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'fechaActualizacion' field.
      * @return This builder.
      */
    public org.TFGInformatica.ContaminacionEstacionDeMedicion.Builder clearFechaActualizacion() {
      fechaActualizacion = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContaminacionEstacionDeMedicion build() {
      try {
        ContaminacionEstacionDeMedicion record = new ContaminacionEstacionDeMedicion();
        record.idelem = fieldSetFlags()[0] ? this.idelem : (java.lang.Integer) defaultValue(fields()[0]);
        record.descripcion = fieldSetFlags()[1] ? this.descripcion : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.m01 = fieldSetFlags()[2] ? this.m01 : (java.lang.Float) defaultValue(fields()[2]);
        record.m06 = fieldSetFlags()[3] ? this.m06 : (java.lang.Float) defaultValue(fields()[3]);
        record.m07 = fieldSetFlags()[4] ? this.m07 : (java.lang.Float) defaultValue(fields()[4]);
        record.m08 = fieldSetFlags()[5] ? this.m08 : (java.lang.Float) defaultValue(fields()[5]);
        record.m09 = fieldSetFlags()[6] ? this.m09 : (java.lang.Float) defaultValue(fields()[6]);
        record.m10 = fieldSetFlags()[7] ? this.m10 : (java.lang.Float) defaultValue(fields()[7]);
        record.m12 = fieldSetFlags()[8] ? this.m12 : (java.lang.Float) defaultValue(fields()[8]);
        record.m14 = fieldSetFlags()[9] ? this.m14 : (java.lang.Float) defaultValue(fields()[9]);
        record.m20 = fieldSetFlags()[10] ? this.m20 : (java.lang.Float) defaultValue(fields()[10]);
        record.m30 = fieldSetFlags()[11] ? this.m30 : (java.lang.Float) defaultValue(fields()[11]);
        record.m35 = fieldSetFlags()[12] ? this.m35 : (java.lang.Float) defaultValue(fields()[12]);
        record.m37 = fieldSetFlags()[13] ? this.m37 : (java.lang.Float) defaultValue(fields()[13]);
        record.m38 = fieldSetFlags()[14] ? this.m38 : (java.lang.Float) defaultValue(fields()[14]);
        record.m39 = fieldSetFlags()[15] ? this.m39 : (java.lang.Float) defaultValue(fields()[15]);
        record.m42 = fieldSetFlags()[16] ? this.m42 : (java.lang.Float) defaultValue(fields()[16]);
        record.m43 = fieldSetFlags()[17] ? this.m43 : (java.lang.Float) defaultValue(fields()[17]);
        record.fechaActualizacion = fieldSetFlags()[18] ? this.fechaActualizacion : (java.lang.CharSequence) defaultValue(fields()[18]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContaminacionEstacionDeMedicion>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContaminacionEstacionDeMedicion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContaminacionEstacionDeMedicion>
    READER$ = (org.apache.avro.io.DatumReader<ContaminacionEstacionDeMedicion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.idelem);

    out.writeString(this.descripcion);

    out.writeFloat(this.m01);

    out.writeFloat(this.m06);

    out.writeFloat(this.m07);

    out.writeFloat(this.m08);

    out.writeFloat(this.m09);

    out.writeFloat(this.m10);

    out.writeFloat(this.m12);

    out.writeFloat(this.m14);

    out.writeFloat(this.m20);

    out.writeFloat(this.m30);

    out.writeFloat(this.m35);

    out.writeFloat(this.m37);

    out.writeFloat(this.m38);

    out.writeFloat(this.m39);

    out.writeFloat(this.m42);

    out.writeFloat(this.m43);

    out.writeString(this.fechaActualizacion);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idelem = in.readInt();

      this.descripcion = in.readString(this.descripcion instanceof Utf8 ? (Utf8)this.descripcion : null);

      this.m01 = in.readFloat();

      this.m06 = in.readFloat();

      this.m07 = in.readFloat();

      this.m08 = in.readFloat();

      this.m09 = in.readFloat();

      this.m10 = in.readFloat();

      this.m12 = in.readFloat();

      this.m14 = in.readFloat();

      this.m20 = in.readFloat();

      this.m30 = in.readFloat();

      this.m35 = in.readFloat();

      this.m37 = in.readFloat();

      this.m38 = in.readFloat();

      this.m39 = in.readFloat();

      this.m42 = in.readFloat();

      this.m43 = in.readFloat();

      this.fechaActualizacion = in.readString(this.fechaActualizacion instanceof Utf8 ? (Utf8)this.fechaActualizacion : null);

    } else {
      for (int i = 0; i < 19; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idelem = in.readInt();
          break;

        case 1:
          this.descripcion = in.readString(this.descripcion instanceof Utf8 ? (Utf8)this.descripcion : null);
          break;

        case 2:
          this.m01 = in.readFloat();
          break;

        case 3:
          this.m06 = in.readFloat();
          break;

        case 4:
          this.m07 = in.readFloat();
          break;

        case 5:
          this.m08 = in.readFloat();
          break;

        case 6:
          this.m09 = in.readFloat();
          break;

        case 7:
          this.m10 = in.readFloat();
          break;

        case 8:
          this.m12 = in.readFloat();
          break;

        case 9:
          this.m14 = in.readFloat();
          break;

        case 10:
          this.m20 = in.readFloat();
          break;

        case 11:
          this.m30 = in.readFloat();
          break;

        case 12:
          this.m35 = in.readFloat();
          break;

        case 13:
          this.m37 = in.readFloat();
          break;

        case 14:
          this.m38 = in.readFloat();
          break;

        case 15:
          this.m39 = in.readFloat();
          break;

        case 16:
          this.m42 = in.readFloat();
          break;

        case 17:
          this.m43 = in.readFloat();
          break;

        case 18:
          this.fechaActualizacion = in.readString(this.fechaActualizacion instanceof Utf8 ? (Utf8)this.fechaActualizacion : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










